name: Build and Deploy Manual

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Cache LaTeX packages
        uses: actions/cache@v3
        with:
          path: ~/.texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/texlive.tlpdb') }}

      - name: Install LaTeX, Pandoc, and Python
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-lang-german \
            texlive-lang-english \
            lmodern \
            python3 python3-pip
            
          pip install pandoc

      - name: Build the manual
        run: |
          cd manual
          make dist

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: manual/build
